# Generated by Django 4.2 on 2023-05-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='Articles/images/')),
                ('text', models.TextField()),
                ('slider1', models.ImageField(blank=True, upload_to='Articles/images/')),
                ('slider2', models.ImageField(blank=True, upload_to='Articles/images/')),
                ('slider3', models.ImageField(blank=True, upload_to='Articles/images/')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
